export const ADD_CART_INGERDIENT = 'ADD_CART_INGERDIENT';
export const DELETE_CART_INGREDIENT = 'DELETE_CART_INGREDIENT';
export const ADD_CART_INGERDIENT_BUN = 'ADD_CART_INGERDIENT_BUN';
export const MOVE_CART_INGERDIENT = 'MOVE_CART_INGERDIENT';
